adblock detect:
  - '- \[[xX]] Anty-adblock'

reklama:
  - '- \[[xX]] Reklama'

kryptokoparki:
  - '- \[[xX]] Wydobywanie kryptowalut'

cookies:
  - '- \[[xX]] Komunikat dot. ciasteczek i polityki prywatności\/RODO'

social filters:
  - '- \[[xX]] Element społecznościowy'

hosts file:
  - '- \[[xX]] Pi-hole, hosts i spółka'

błąd:
  - '- \[[xX]] Błąd'

pytanie:
  - '- \[[xX]] Pytanie'
